name: gha action release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: create release
    runs-on: ubuntu-20.04
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        release-type: simple
