name: gha action release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  release:
    name: create release
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Determine release version
      id: determine_version
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -z "$LAST_TAG" ]; then
          LAST_TAG="1.0.0"
        fi
        # Install conventional-recommended-bump
        echo "{\"version\":\"$LAST_TAG\"}" > package.json
        npm install -g conventional-recommended-bump

        # Get the recommended version bump
        VERSION_BUMP=$(conventional-recommended-bump)
        echo "NEW_VERSION=$VERSION_BUMP" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_VERSION }}
        name: Release ${{ env.NEW_VERSION }}
        draft: false
        prerelease: false
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
