name: gha action release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: create release
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: auto-it/setup-auto@v1

      - name: Run auto
        run: |
          NEW_VERSION=$(auto version)

          echo "NEW_VERSION=$NEW_VERSION"
          
          # Create a new Git tag
          git tag -a "v$NEW_VERSION" -m "Release $NEW_VERSION"
          git push origin "v$NEW_VERSION"

          auto release
          auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
